FROM python:3.12-slim

WORKDIR /app

# Mengatasi pembuatan file .pyc & memastikan log langsung ke terminal
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# salin modul & file backend
COPY module/ ./module/
COPY main.py

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]